name: Java CI with Maven

on:
  push:
    branches: [ master ]

defaults:
  run:
    working-directory: ./TruckBooking
    
jobs:
  build:
    runs-on: ['self-hosted', 'Linux', 'X64', 'main' ]

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'

    # Step to upload a file from the host
    - name: Upload file
      run: cp /home/ubuntu/firebaseKey.json ./TruckBooking/src/main/resources

    - run: sudo docker container stop load-container || true  
    - name: Build with Maven
      run: mvn -B package --file pom.xml
       
    - run: cd ~/actions-runner/deploy/loadsApi/loadsApi/TruckBooking
    - run: sudo docker container rm load-container || true
    - run: sudo docker image rm load || true
    - run: sudo docker build -t load .
    - run: sudo docker run --env-file /home/ubuntu/envProd.properties -p 8080:8080 --name load-container  load | echo "success" 
